### ISSUE TITLE
Registration?

### ISSUE THREAD

**Issue by vpelss** [vkeselj/CGI-AuthRegister#2]
Thanks for the code. 

When you use the term registration, what do you mean?
When I see the word registration, I think account creation.

I will have to add that for my project.

**Comment by vkeselj** [comment]
Yes, exactly: registration means "user registration" which is account creation.

**Comment by vpelss** [comment]
I can't see where your code does that though... (without modifying it).

Even some of your text says to create the accounts manually in the text flat file db.

**Comment by vkeselj** [comment]
Good point.  Yes, it is currently assumed that a moderator would add a user manually to users.db.  I have some code for users to register themselves but I will need to modify the module to make it easy to use in this way.

**Comment by vkeselj** [comment]
I added functionality for new users to register themselves, and confirm their email by clicking the confirmation code.  It is added in the example 8 and also in documentation, at the beginning.
